name: "cosine_similarity"
backend: "python"
max_batch_size: 0

input [
  {
    name: "embeddings"
    data_type: TYPE_FP32
    dims: [-1, 768]
  }
]

output [
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [-1]
  }
]
